from data import functionDemo
from data import enemyData
from data import playerData
from data import noMagic
from data import knightData
import time

playerName = str(playerData.name)
playerHP = str(playerData.HP)
playerMana = str(playerData.mana)
playerAttack = str(playerData.attack)
playerDefence = str(playerData.defence)
playerSpeed = str(playerData.speed)
playerMagicAttack = str(playerData.magicAttack)
playerWeapon = str(playerData.weapon)

def marinaLevelUp(playerHP,playerMana,playerAttack,playerDefence,playerSpeed,playerMagicAttack,playerWeapon):
    wr = open('data\playerData.py', 'w')
    wr.write("name ='"+marinaName+"'\n")
    wr.write('HP='+playerHP+'\n')
    wr.write('mana='+playerMana+'\n')
    wr.write('attack='+playerAttack+'\n')
    wr.write('defence='+playerDefence+'\n')
    wr.write('speed='+playerSpeed+'\n')
    wr.write('magicAttack='+playerMagicAttack+'\n')
    wr.write("weapon='"+playerWeapon+"'\n")


print("**********************************************************")
print("     ___       __      .______    __    __       ___      ")
print("    /   \     |  |     |   _  \  |  |  |  |     /   \     ")
print("   /  ^  \    |  |     |  |_)  | |  |__|  |    /  ^  \    ")
print("  /  /_\  \   |  |     |   ___/  |   __   |   /  /_\  \   ")
print(" /  _____  \  |  `----.|  |      |  |  |  |  /  _____  \  ")
print("/__/     \__\ |_______|| _|      |__|  |__| /__/     \__\ ")
print("")
print("**********************************************************")

print("")
print("")
print("")
time.sleep(2)
input("YEAR - 199X")
print(" ")
input("The sun shines on a mobile home sitting on top of a grassy hill.")
input("A girl with long blonde hair sits slumped by the window of the vehicle, looking out onto the ocean spread out before her.")
input("She waters a shriveled looking plant sitting on the windowsill.")
input("She sighs, and traces her finger along the dry leaves of the plant. She has a moment of empathy for it- they would agree that it was far too hot, even for June.")
marinaName = input("What is the girl's name? --> ")
if marinaName == '' or ' ':
    marinaName = 'Marina'
input("Her name is "+marinaName+".")
marinaLevelUp('20','10','4','0.5','1','5','melee')
input("Today, like all days before it, felt empty for "+marinaName+".")
input("Despite it being her 17th birthday, she had found herself pacing up and down her home like a bored tiger in a zoo.")
input("Though the walls did not physically keep her trapped, her father had crafted her a prison made out of words.")
input("By this, I of course mean that he gave her strict instructions not to leave until he came back with dinner reservations.")
input("It would take a while for him to find a restaurant that would take them. However, it had been over an hour and a half, and "+marinaName+" was starting to get just a tiny little bit bored.")
input("Sighing again, she looked over her shoulder at the door. She so desperately wanted to get out and stretch her legs, but she had never disobeyed her father before.")
input("She wasn't sure that she knew how. Although... she had read every book in her home, and they didn't have a TV, and the fresh air looked very inviting. ")
input("Surely... surely, it wouldn't hurt anybody if she were to go out and do a lap around the caravan. Just for a minute. Just to get some air in her lungs. She felt like a gerbil in a microwave, cooped up in her home.")
input("No! No. Dad said no, so she wouldn't. She turned away from the door and went back to staring at the sea...")
input("Less than 10 seconds later, "+marinaName+" was halfway down the hill, her lacy white dress billowing behind her as she broke into a sprint.")
input("Before she could enter the town however, she caught the eye of a wild looking dog patroling the small dirt roads that surrounded it. It bared its teeth at her.")
input("There was no way she just walk past it. Her heart beat hard in her chest and her fight or flight reflexes gave her two ways out.")
input("She clenched her fist and made her body wide...")
input("It's time...")
input("To FIGHT!")
dogWon = noMagic.fight('Wild Dog',marinaName,playerData.HP,enemyData.enemyHP,playerData.mana,playerData.attack,enemyData.enemyAttack,playerData.defence,enemyData.enemyDefence,playerData.magicAttack,playerData.speed,enemyData.enemySpeed,enemyData.enemyMana,enemyData.enemyMagicAttack,'melee','melee')
if dogWon == True:
    input("\nWow.")
    input("Just... Wow.")
    input("I have no words for what you just did.")
    input("I know you were defending yourself from that dog but damn...")
    input("You really went ahead and killed it.")
    input("You killed that dog.")
    input("I didn't mention it because I didn't think it was relevant, but that dog belonged to a little boy.")
    input("His family didn't have a lot of money because his dad passed away last year but they still managed to give him that dog.")
    input("It made him so happy, and he had been so sad for so long.")
    input("Do you want to know what it was called?")
    input("Its name was Andre.")
    input("It was named after the boy's father.")
    input("You disgust me.")
    input("You monster.")
    input("...")
    input("Haha just kidding, the dog didn't die "+marinaName+ "just kicked it and it ran away.")
    input("Got you, though.")
    print("")
    input("After coming out triumphant against poor Andre, "+marinaName+" breathed a sigh of relief and wiped her brow.")
    input("'Good grief,' she thought, 'that was an awful lot of excitement.'")
    input("The path was now clear for her to advance with her quest to get some air in her lungs, though the shock of her encounter had given her more than enough.")
    input("She looked back up the hill, the leftover adrenaline making her consider turning back.")
    input("But no, she had already broken the rules, there couldn't be any harm in exacerbating the break a tiny bit more.")
    input("She would have to move stealthily throughout the town, lest her father catch her in the act of teenage rebellion.")
    input("The town centre was a bustling hub of people, going about their business.")
    input("They browsed market stalls filled to the brim with sun-dried bread, tomatoes and beautiful scarves with intricate patterns.")
    input("White buildings reflected the suns rays back at the townspeople, their brown terracotta roofs absorbing its heat.")
    input("Past the market, light bounced off of the ocean's waves and glittered the faces of the various businesses that lined the boardwalk. Patrons sat outside cafes, enjoying local grown coffee.")
    input("Hotels resembling small palaces catered to the upper class, providing views of the beach; everything from the shutters on the windows to the bright paints on the walls was perfect.")
    input("Part of "+marinaName+" found them beautiful. Another part found it sad, as she knew that she would never enter those buildings.")
    input("She couldn't, even if she and her dad didn't move from town to town on a regular basis.")
    input("Another part thought that the other two parts were massive nerds. That was the loudest part.")
    input("You see, the hotels were made for Blessed nobility.")
    input("Members of high society had come to the town to drink wine and eat grapes and gaze at the infinite expanse of the sea for over a hundred years.")
    input(marinaName+" didn't belong to that class. She was Mortal. The black ‘X' tattooed on her right hand told her so.")
    input("When "+marinaName+" was younger, she used to play a game whilst walking through the streets of a new, unfamiliar town with her father.")
    input("She liked to guess what abilities a Blessed person had when she passed them.")
    input("Most of the time, it was fairly hard to guess. Big guy? Maybe super-strength. Loose fitting clothing? Maybe a shapeshifter.")
    input("Tentacles spilling out of every hole and orifice, giving them the appearance of some Old God, an eldritch horror from beyond the Angel's Playground?")
    input("OK, that one was pretty easy.")
    input("Suddenly, the sound of police sirens filled the air. Instantly, the small groups of Mortals that gathered by the side of the street scattered.")
    input(marinaName+" looked frantically around her. Although it wasn't a crime to be a Mortal, some cops sure did act like it was.")
    input("It makes their jobs a lot easier when they can pin a crime on a Mortal bystander rather than actually having to go and find the criminal.")
    input("This is, of course, a very bad and unjust thing, and it is very fortunate that this type of thing NEVER happens in the world you live in, dear reader.\n")
    input("The sirens were getting louder, and "+marinaName+" was no closer to finding a hiding spot. She was beginning to panic when she heard the hoot of a whistle behind her.")
    input("Turning towards the ocean, she was greeted by a ferry offering rides to a nearby island.")
    input("It was small, old, and it didn't have a roof, but it was a way out, so it was good enough for "+marinaName)
    input("She hastily skipped across the wooden boards of the dock and held out a few coins to the driver.")
    input("Captain?")
    input("Pilot?")
    input("Whatever.")
    input("The coins had the stern profile of Fidicen's King adorned on their faces. His profile was everywhere, from the coins, to posters on busses, to regular TV broadcasts.")
    input("Never smiling, his wrinkled face looked permanently slightly bored.")
    input("When the driver...")
    input("Helmsman!")
    input("...reached down to take the coins, "+marinaName+" snuck a quick look at their hand. ")
    input("An 'X' tattoo. Darn. She would have liked to guess their Blessing.")
    input("As there were no other passengers, she had the luxury of being able to choose to sit in the centre of the ferry, to avoid seasickness.")
    input("It lurched forwards, and she was off, escaping the police... and her father.")
    input("Oh dear.\n")

    input(marinaName+" was dreaming. ")
    input("She sat on a plump red chair in a theatre. A seemingly infinite number of these chairs filled the room in rows, ascending and ascending to the heavens.")
    input("A girl with long hair and a white dress danced on the stage; her arms and legs making wide, circular movements that made the bottom of her dress spin.")
    input("The backdrop ebbed and flowed as if it couldn't decide what it was supposed to be. ")
    input("The girl stopped dancing and looked up at the ceiling. ")
    input(marinaName+" followed her gaze, wondering what could be so interesting that it could have the power to make her stop everything and gaze at the blazing sun.")
    input("A bird, apparently. No, actually, two birds. And two more. ")
    input("Slowly, hundreds of blackbirds flocked in from the wings of the stage, all flying in formation, filling the sky and billowing above the girl's head. ")
    input("The theatre turned dark as the birds blocked out the light. ")
    input("Then the girl began to scream, her hands gripping the side of her head, her elbows shielding her ears. ")
    input("The birds swirled around her body as she assumed the foetal position, and she then disappeared behind a curtain of feathers.")
    input("When the birds parted and flew away in groups, the girl was standing up again, looking away from the audience. ")
    input("She was wearing a uniform over her dress– a dark blue blazer, like the ones that the Knights in the army wear. ")
    input("The girl turned around and "+marinaName+" felt nauseous by what she saw. ")
    input("Her eyes were glassy and bloodshot, her head slumped at an angle. Her skin was blue and bloated, veins clearly visible, her smiling lips pale. ")
    input("What she saw was her own drowned body. ")
    input("'I want this dream to be over now,' she thought. ")
    input("'I want to wake up,'")
    input("'I don't want to look at this anymore, I'm done, I want to leave,'")
    input(marinaName+" dug her nails into the palms of her hands in an attempt to try to wake herself up, but she couldn't feel anything.")
    input("She looked down and her skin was blue. She screamed.")
    input("When she looked up, she was surrounded by darkness and she was trapped in a glass case.")
    input("She banged on the glass, but to no avail. Water began to pour down from above.")
    input("It wasn't long before the water was at her knees, soaking the bottom of her dress. ")
    input("She saw a figure in the darkness. It was her father. He stood there, watching, ignoring "+marinaName+"'s screams.")
    input("The water reached her shoulders. ")
    input("He looked slightly bored as "+marinaName+" began to cry a deep, life-fearing sob.")
    input("She stopped sobbing as her head was submurged.")
    input("Her raspy throat stopped screaming as her lungs ran out of air and")
    input("her lungs filled with water and")
    input("her father watched with dead eyes and")
    input("her chest hurt so, so much and")
    input("she wanted it to stop and ")
    input("her tank filled with blood that came from her mouth and\n")

    input("She woke up.")
    input("...\n")
    input("She shot up so fast that the muscles in her abdomen hurt. Gripping her seat, she steadied herself and let her heart slow down.")
    input("It beat hard, like someone was pounding on her chest, trying to perform CPR, and the spaces between each pulse filled with terror. ")
    input("Her eyes were open but all she could see was her father's dead eyes and her own waterlogged body. ")
    input("When her vision cleared of nightmares, she was reminded that she was on a boat, drifting slowly away from her real father on the mainland. ")
    input("She looked back and found that they hadn't travelled far from the coast, she could still see it far off in the distance. ")
    input("However, that wasn't the only thing she could see. Before she set off, the sky was as blue as the ocean, as if it was a mirror that reflected the calm sea below. ")
    input("Now, the sky was grey, the waves violent and she and everything had been drenched.")
    input("The sea moved like a creature that couldn’t quite decide on its form, its violent waves lashing out and doubling back on itself.")
    input("The waves rocked the boat, the ocean trying to shake the contents of it into the ocean. ")
    input("After that dream, "+marinaName+" was fairly sure that drowning might have been her new worst fear. Oh, how she wished she had developed that fear at literally any other time. ")
    input("'Miss? Ma"+"‘"+"am? What"+"‘"+"s going on?' she asked, addressing the helmsman.")
    input("'Beats me! The waves just got really wild a few minutes ago and now they"+"‘"+"re like this!' she said, clearly just as terrified as "+marinaName+". ")
    input("When the helmsman turned to her, she realised that she was very young. Not much older than her, in fact. How hadn't she noticed that before? ")
    input("She had short ginger hair that stuck up a bit at the front, and on her exposed right bicep she had a tattoo of an anchor.")
    input("'Oh my goodness, oh my goodness… Are we going to be OK?' she said, pacing and flapping her hands, trying to get rid of the adrenaline. Bloody useless adrenal glands. ")
    input("It's awfully hard to either fight or flight from the ocean. What with it being a massive body of water and not, say, a predator. ")

    print("'I don"+"‘"+"t know! I"+"‘"+"m really, really sorry. I told my fucking dad that I wasn"+"‘"+"t ready to run my own boat, but did he listen? HA! Does he ever?... ")
    print("He only cares that he has one more bloody boat on the sea and that his wallet gets fatter. ")
    input("I"+"'"+"m sorry, I"+"‘"+"m sorAGHHG–' said the helmsman, her rambling cut short by a wave hitting the ferry.")
    input(""+marinaName+" fell onto her back as the front of the boat pointed to the sky and crashed down again. ")
    input("As the dull pain of the fall settled into her skull, the realisation that this other person had a backstory shocked her. ")
    input("She knew that she wasn't the centre of the universe, but she had always intended for this person to be... well, to be a NPC in the game that was her life. ")
    input("The fact that the only fear she felt was for her own safety scared her. She stood up with assistance from the railing and grabbed the helmsman's shaking shoulder. ")
    input("'What"+"‘"+"s your name?' she asked.")
    input("'What?' the helmsman said, caught off guard.")
    input("'I don"+"‘"+"t want to drown with you without even knowing your name. Please.' ")
    input("'Sam. It's Sam.'")
    input("'Pleasure to meet you, Sam. I"+"‘"+"m "+marinaName+".'")
    input("'Nice to meet you too, "+marinaName+",' Sam smiled sadly and gave a salute.")
    input("A surge of water hit the boat. It tipped… ")
    input("and they were brought underwater. \n")

    input("The breath in "+marinaName+"'s lungs immediately escaped her as she plunged into the water. Her muscles stiffened, and her jaw tightened.")
    input("Her mind was filled with absolute certainty that she was going to die.")
    input("She sank further.")
    input("She wanted to swim up, but she was completely paralysed. She poured every ounce of her will into moving her legs, but she just couldn't swim.")
    input("She sank further.")
    input("She needed to get out of there. She needed to swim.")
    input("She sank further.")
    input("She thought of her dad. She felt horrible for all the times she got upset at him. She never even said goodbye. She just left. ")
    input("Now she was going to die, and he'd never know what happened to her.")
    input("She sank further.")
    input("The water began to crush her now. The pressure was just too much. She just wanted it to be over quickly. The possibility of a slow death haunted her.")
    input("She sank further.")
    input("She wasn't crying, but the heat behind her eyes was building and the emptiness in her chest was tightening. Her chest began to throb with regret.")
    input("She sank further.")
    input("Please relax, she thought. You must swim.")
    input("She sank further.")
    input("If you don't relax you will die.")
    input("She sank further.")
    input("She closed her eyes and waited for death to come. ")
    input("She sank further,")
    input("and further,")
    input("and further.")

    surviveMagicActivate = False
    while surviveMagicActivate == False:
        checkMagicActive = input("\nENTER (m) TO SURVIVE --> ")
        if checkMagicActive == 'm':
            surviveMagicActivate = True

    input("\nAnd then something snapped.")
    input(""+marinaName+" felt a connection to something as if it were another limb. When she manoeuvred it around, testing its limits, she felt as if nothing had come more naturally.")
    input("She fell through the water a bit more, but then stopped as her body began to stay perfectly upright. ")
    input("She was no longer deep in the depths of the sea, no, she was somewhere else. ")
    input("The air smelled like something her dad had forgotten at the back of her fridge, something that had begun to fester and rot. ")
    input("Her ears rung as the violent sound of rushing water and her own screams subsided. ")
    input("There were no discernible walls or ceilings of any kind– she was standing in an abyss. ")
    input("A old man stood in the abyss, facing "+marinaName+". She recognised him instantly. It would be hard not to. ")
    input("He stared at her for a while, inspecting her intently, before smiling like a shark and fading away.")
    input("What happened next was a blur. "+marinaName+" shot up through the water, the sea swirling around her and propelling her upwards. ")
    input("She was thrown around like a rag doll, bubbles filling her vision—it took her a second to realise that they came from her mouth. She was screaming. ")
    input("The water around her became a swirling vortex. She was spinning out of control, rising to the surface.")
    input("suddenly, she was dry again. She felt sand under her hands, the sun on her legs and a shadow over her eyes. She looked up. She was back on the beach. ")
    input("The storm had cleared, and her hair was no longer damp. Also, and there was a 20-foot golem made of water poking out of the ocean. ")
    input("As its arm returned to its side, it became clear that this is what carried her back to the shore. ")
    input("Its face was featureless, and its legs (if water golems even have legs) must have been submerged beneath the waves. ")
    input("Understandably, "+marinaName+" screamed and scrawled away from it like a crab. ")
    input("Most people would do the same in her situation. ")
    input("Its form shook for a moment, and then burst, the water making up its body falling back into the sea.")
    input("'What in ACTUAL Judeo-Christian Hell?' she exclaimed. ")
    input("Frightened, yet curious, she reached out like she did when she was sinking– as if the water itself was a part of her body. ")
    input("She closed her eyes searched with her mind for Sam. She felt a third eye open and found her struggling beneath the waves a few miles away. ")
    input("The ocean was dark, and infinite, and terrifying, but she could see it all.")
    input("So… she has water powers? Wow. Like, magic? Huh. What a surprising then of events. I think it's fair to say that nobody saw that one coming.")
    input("Clenching her fist, she raised her arm and moved it to her right. ")
    input("Just as she willed there to be, a hand carrying Sam burst out of the water and approached her before finally dropping her far along the beach, away from "+marinaName+".")
    input("Explaining why she had hydrokinesis even though she had the Mortal's Mark would be a real headache, and she didn't even know herself. ")
    input("However, she did know one thing. ")
    input("The look on her father's face when she told him was going to be spectacular.\n")

    print("\n***LEVEL UP!***")
    time.sleep(1)
    print("Acquired the ability to use [Speed UP^^], [Defence UP^^] and [Water Spear] in battle!")
    time.sleep(1)
    print("Health Points - 25")
    time.sleep(1)
    print("Attack - 4")
    time.sleep(1)
    print("Defence - 1")
    time.sleep(1)
    print("Speed - 1")
    time.sleep(1)
    print("Mana - 10")
    time.sleep(1)
    print("Magic Attack - 5")
    time.sleep(1)
    print("Fear of Water - 100%")
    time.sleep(1)
    input("...")
    marinaLevelUp('25','10','4','0.5','1','5','melee')
          
    input("\nIt was getting dark now, the evening sunlight basking the seaside town in an amber glow.")
    input("The vibrant greens of the grass covered hill where "+marinaName+" had taken up residence were now shades of dull jade.")
    input(marinaName+"'s father had his back to her as he stood outside the mobile home.")
    input("He wasn't a young man- what was left of his hair was a soft grey and wrinkles plagued his eyes and forehead.")
    input("He insisted on wearing an old pair of half-moon spectacles, which perched on the end of his nose and gave him the appearance of a boarding school professor")
    input("He was on the phone- a massive, brickish thing- likely trying to contact the police.")
    input("When "+marinaName+" called up to him, he put the phone down from his ear and gave a look of half relief and half annoyance.")
    input("'Where in the heavens have you been?' he asked in an exasperated tone.")
    input("'It's a long story, and I'm very sorry, but-' "+marinaName+" began.")
    input("'You had me worried sick! What if something had happened to you?' her father interjected.")
    input("His arms flailed around in anger, making him look like he was venting to an audience.")
    input("'I'm sorry, but Dad-'")
    input("'You don't know this area! I told you to stay here for a reason, dear girl!'")
    input("'Dad-'")
    input("'I'll have to call off-'")
    input(marinaName+" shut her eyes and balled her fists and said, 'Dad, I have magic powers!'")
    input("She felt a twinge of guilt for shouting at her father.")
    input("When her father said nothing in return, she looked up. Fear painted his face, his eyes wide like a deer in headlights.")
    input("'You... you...' he stammered.")
    input("'I was drowning in the sea and I could just... DO it! I could move water with my mind! It felt so peculiar yet so... right!'")
    input("'Hush! Did you see Him? When you first used your ability, did He appear?'")
    input("'Yes, but I thought it was just a hallucination. Hold on... how could you know?' "+marinaName+" asked. Did her father know more than he was letting on?")
    input("He patted down his pockets, looking for the keys to the mobile home. 'Dear child, you are in grave danger. We must leave. Now.' ")
    input("Before "+marinaName+" could ask why, a faint buzzing sound filled her ears.")
    input("Behind her, a fleet of helicopters began to creep over the horizon like a flock of birds.")
    input("'It's too late. He knows we're here. Get in the caravan. Hurry!'")
    input("Quickly, "+marinaName+" was ushered into the mobile home.")
    input("Before closing the door, her father took his spectacles off and placed them on the counter inside.")
    input("'Stay hidden', he commanded, 'and whatever you do, don't leave.")
    input("It was hard to hear him over the sounds of the approaching helicopters, but she understood.")
    input("She hid under the counter, and waited. Moments passed, and the sounds became deafening, and then silence fell.")
    input("The helicopter's engines turned off. "+marinaName+" heard someone walking towards the caravan.")
    input("She pressed her ear up against the wall and listened.")
    input("\nOutside, a man in a dark blue blazer approached "+marinaName+"'s father, who stood by the door to the caravan, guarding his daughter inside.")
    input("'Edmund. It has been too long,' the man in blue said.")
    input("'I'm afraid that I can't agree. Would you consider coming back later?' her father retorted.")
    input("'Ah, I remember that wit. That's why you were called the comedian of the Pneuma Laboratory. Of course, up until you left it. I think they now call you the traitor.'")
    input("'So, who am I really talking to? The bearded manchild in a suit that I see before me, or... You?'")
    print("'It's Me, my friend. It's always been Me. Now, I'm sorry that I'm rushing things, but I'm afraid that I'm in quite a hurry.")
    input("You have something that belongs to me. I'm here to take it back.'")
    input("'That's not going to happen, I'm afraid'")
    input("'Be rational, Edmund. Come home. You were ever so useful to me. You could have your own laboratory. Your own manor. No more running... no more hiding.'")
    input("'I may not have been the best father, but I know what is right and what is not. I would rather die than rejoin you,' Edmund said triumphantly.")
    input("The other man sighed. 'I thought you were smarter than that. Oh well. Your wish is my command. Men, fire.'")
    input("And, just like that, "+marinaName+"'s father died.")
    input("'NO!' "+marinaName+" screamed. She felt like she had been shot too, the loss of her father created a chasm in her chest.")
    input("She burst through the door with murderous intent. Water from the air and from the ground swirled around her hands with out her asking it to.")
    input("Four knights in blue uniforms pointed their guns at her. She didn't care.")
    input("She was going to FIGHT, and she was going to kill all of them.")
    functionDemo.fight(knightData.name,marinaName,playerData.HP,knightData.HP,playerData.mana,playerData.attack,knightData.attack,playerData.defence,knightData.defence,playerData.magicAttack,playerData.speed,knightData.speed,knightData.mana,knightData.magicAttack,playerWeapon,knightData.weapon,)

    input("\n\nOne down.")
    functionDemo.fight(knightData.name,marinaName,playerData.HP,knightData.HP,playerData.mana,playerData.attack,knightData.attack,playerData.defence,knightData.defence,playerData.magicAttack,playerData.speed,knightData.speed,knightData.mana,knightData.magicAttack,playerWeapon,knightData.weapon,)

    input("\n\nAnother.")
    input("She swept her in front of her face and a barrier of water absorbed the oncoming bullets.")
    input("Water from deep under the hill split up through the ground and swirled around in the air, making a tendril.")
    input("The end of it turned sharp, and impaled a helicopter above, causing it to burst into flames. She used the water as a pedestal and grew taller and taller in the air.")
    input("The ground continued to split, with more water spilling out to drown the remaining knights, but a throbbing began to appear in "+marinaName+"'s head.")
    input("It was becoming too much to handle. She threw her arms out wide and released all of the water in her grasp in one final blast, and fell unconscious.")
    input("\n...")
    print(" ")
    
    input(marinaName+" was dreaming again.")
    input("She and her father, Edmund, sat on a blanket on the beach. The sun crested over the horizon as the day reached its conclusion.")
    input("Edmund played a slow, sombre song on a guitar as he looked out onto the sea.")
    input("'Dad?' "+marinaName+" said, turning to her father.")
    input("'Yes, dear?' he replied, still playing his song.")
    input("'I'm going to miss you.'")
    input("He stopped playing.")
    print("'There is an old saying. It more or less says that people have three faces- one, that we show to the world, another, that we show to those dear to us, and")
    print("the last being our true face. Now, I believe that everyone has a way of expressing this elusive third face. Everybody has an instrument to play their own song.")
    input("When you miss me, remember this song.' At that, he began to play the mournful song again.")
    input(marinaName+" pondered this for a moment, and said, 'What is is my instrument?'")
    input("'Yours is your voice, my girl.'")
    input("'M-my voice? How so? I can't sing, I'm not a poet, I can't speak my mind... I couldn't use it to save you.'")
    input("'The time will come when you will find your voice.'")
    input("'How can you know?'")
    input("Edmund turned to her.")
    input("'Because you must,' he said.")
    input(marinaName+" woke up.")
    
        


